# LongName is the expanded name of the site
LongName: Carleton College CRUG Cluster
# Description is a brief description of your site
Description: CMC building at Carleton College

# AddressLine1 is the street address of the site
AddressLine1: Carleton College
### AddressLine2 (optional) is the second line of the street address
# AddressLine2: Room 101
AddressLine2: One North College Street
# City is the city the site is located in
City: Northfield

# Country is the country the site is located in
Country: United States
### State (optional) is the state or province the site is located in
# State: Wisconsin
State: Minnesota
### Zipcode (optional) is the zipcode/postal code of the site
# Zipcode: "01234"
Zipcode: "55057"


# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 44.4613633
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -93.1585491
